name: Deploy EduLearn Pro

on:
  push:
    branches: [ "main"]
    branches-ignore: ['ignore']
    paths: ".github/*"
  
  pull_request:
      branches: [ "main"]
  workflow_dispatch: 


jobs:
  build-app:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: run oneline script
        uses: echo "Hello, World!"
        

      - name: run a multiline script
        run: 
          echo "Hello, World!"
          echo "This is a multiline script"
  build-api:
    runs-on: windows-latest
    steps:
      - run: echo "Building api"
  build-db:
    needs: build-app
    runs-on: windows-2022
    steps:
     - run: echo "Hello, World!"

  package: 
    needs: [build-app,build-db]
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Hello, World!"


 
